version: '3.8'

services:
  # PostgreSQL database with CERIF data model
  postgres:
    build:
      context: .
      dockerfile: db.dockerfile
    image: ${REGISTRY_URL}/myRIMS/database:latest
    restart: always
    environment:
      POSTGRES_USER: rims_admin
      POSTGRES_PASSWORD: rims_password
      POSTGRES_DB: rims_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rims_admin -d rims_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Metabase for user interface
  metabase:
    build:
      context: .
      dockerfile: metabase.dockerfile
    image: ${REGISTRY_URL}/myRIMS/metabase:latest
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: rims_admin
      MB_DB_PASS: rims_password
      MB_DB_HOST: ${DB_HOST:-postgres}
      JAVA_OPTS: "-Xmx2g"
    volumes:
      - metabase_data:/metabase-data
    ports:
      - "${METABASE_PORT}:3000"
    depends_on:
      postgres:
        condition: service_healthy

  # Airbyte for data integration
  airbyte-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airbyte
      POSTGRES_PASSWORD: airbyte
      POSTGRES_DB: airbyte
    volumes:
      - airbyte_db_data:/var/lib/postgresql/data
    ports:
      - "${AIRBYTE_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airbyte -d airbyte"]
      interval: 10s
      timeout: 5s
      retries: 5

  airbyte-server:
    build:
      context: .
      dockerfile: airbyte.dockerfile
    image: ${REGISTRY_URL}/myRIMS/airbyte:latest
    restart: always
    environment:
      DATABASE_HOST: ${AIRBYTE_DB_HOST:-airbyte-db}
      DATABASE_PORT: 5432
      DATABASE_DB: airbyte
      DATABASE_USER: airbyte
      DATABASE_PASSWORD: airbyte
    volumes:
      - airbyte_workspace:/tmp/workspace
      - airbyte_data:/data
    ports:
      - "${AIRBYTE_SERVER_PORT}:8001"
    depends_on:
      airbyte-db:
        condition: service_healthy

  airbyte-webapp:
    image: airbyte/webapp:latest
    restart: always
    ports:
      - "${AIRBYTE_WEBAPP_PORT}:80"
    depends_on:
      - airbyte-server

volumes:
  postgres_data:
  metabase_data:
  airbyte_db_data:
  airbyte_workspace:
  airbyte_data:
