services:
  # PostgreSQL database with CERIF data model
  postgres:
    image: postgres:15
    container_name: rims-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rims_admin
      POSTGRES_PASSWORD: rims_password
      POSTGRES_DB: rims_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rims_admin -d rims_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Metabase for user interface
  metabase:
    image: metabase/metabase:latest
    container_name: rims-metabase
    restart: unless-stopped
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: rims_admin
      MB_DB_PASS: rims_password
      MB_DB_HOST: postgres
      # Add Java options to increase memory
      JAVA_OPTS: "-Xmx2g"
    volumes:
      - metabase_data:/metabase-data
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  # Note: Airbyte is not included in this docker-compose.yml file
  # Please use the official Airbyte Docker Compose file for setting up Airbyte
  # See README.md for instructions

volumes:
  postgres_data:
  metabase_data:
